#!/usr/bin/bash
waybar=~/.config/waybar
scripts=$waybar/sound

cooldown=0.1

pid="$(pgrep cava)"
while :
do
    case "$1" in
        "arrow-icon")
            if [ $($scripts/soundbar_state) = 0 ]; then
                echo "■"
            else
                echo "■"
            fi
            ;;
        "cava-icon")
            if [ $($scripts/soundbar_state) = 0 ]; then
                if [ "$pid" == "$(pgrep cava)" ]; then
                    printf "[general]\nframerate=160\nbars = 7\n[output]\nmethod = raw\nraw_target = /dev/stdout\ndata_format = ascii\nascii_max_range = 7\n" | cava -p /dev/stdin | sed -u 's/;//g;s/0/▁/g;s/1/▂/g;s/2/▃/g;s/3/▄/g;s/4/▅/g;s/5/▆/g;s/6/▇/g;s/7/█/g;' &
                    temp_pid="$(expr $! - 1)"
                fi
            else
                cava_pids=("$(pgrep cava)")
                if [[ " ${cava_pids[*]} " =~ ${temp_pid} ]] ; then
                        echo $temp_pid > /tmp/accr
                        if [ ! -z $temp_pid ]; then
                            kill $temp_pid
                        fi
                fi
                echo ""
            fi
            ;;
        # "media")
        "pipewire-icon")
            if [ $($scripts/soundbar_state) = 0 ]; then
                wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100}'
            else
                echo ""
            fi
            ;;
        *)
            if [ $($scripts/soundbar_state) = 0 ]; then
                echo "     "
            else
                echo ""
            fi
            ;;
    esac
    sleep $cooldown
done