#!/bin/sh

WALLP1 = $HOME/.config/hypr/themes/winter/wallpapers/Planet.png
WALLP2 = $HOME/.config/hypr/themes/winter/wallpapers/o8o22e7f45h91.webp

killall swaybg

sleep 1

### IMAGES ###
# swaybg -m fill -i $HOME/.config/hypr/themes/winter/wallpapers/Planet.png &
# swaybg -m fill -i $HOME/.config/hypr/themes/winter/wallpapers/PandaSamurai.webp &
# swaybg -m fill -i $HOME/.config/hypr/themes/winter/wallpapers/GreenGlass.webp &
# swaybg -m fill -i $HOME/.config/hypr/themes/winter/wallpapers/tits.png &
# swaybg -m fill -i $HOME/.config/hypr/themes/winter/wallpapers/tits_inv.png &
swaybg -m fill -i $HOME/.config/hypr/themes/winter/wallpapers/background1.png &
# swaybg -m fill -i $HOME/.config/hypr/themes/winter/wallpapers/background1inv.png &
# swaybg -m fill -i $HOME/.config/hypr/themes/winter/wallpapers/tits2.png &

# ### COLORS ###
# swaybg -c "#F22555" & # just a dark color (obsidian color..)
