#!/bin/sh

hypr=$HOME/.config/hypr
wallpaper_folder=$hypr/themes/winter/wallpapers

wallpaper_location="$(ls $wallpaper_folder | wofi --show dmenu)"

$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/themes/winter/scripts/wallpaper

# echo "~/.config/hypr/themes/winter/wallpapers$wallpaper"
# swaybg -m fill -i "$HOME/.config/hypr/themes/winter/wallpapers/$wallpaper" &
